FROM node:18 as build

WORKDIR /app

COPY . .

RUN npm i --legacy-peer-deps

RUN npm run build:production

FROM nginx:1.24-alpine as prod

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/dist .

RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx

EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]
