FROM node:14 as build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build:staging

FROM nginx:1.24-alpine as prod

COPY /frontend/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/dist .

RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx

EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]
